application: q-action
version: version-1-3
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: latest
- name: django
  version: 1.4


builtins:
- remote_api: on
 
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /favicon\.ico
  static_files: /images/favicon.ico
  upload: static/images/favicon\.ico

- url: /apple-touch-icon*\.png
  static_files: /images/apple-touch-icon*\.png
  upload: /images/apple-touch-icon*\.png


- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: /subscribe/.*
  script: main.py
  login: required

- url: ./info/.*
  script: main.py

- url: .*
  script: main.py
