application: q-action
version: version-1-1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: latest
- name: django
  version: 1.3


builtins:
- remote_api: on
 
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: /subscribe/.*
  script: main.py
  login: required

- url: ./info/.*
  script: main.py

- url: .*
  script: main.py
