application: q-action
version: beta-2
runtime: python
api_version: 1

builtins:
- remote_api: on
 
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: /subscribe/.*
  script: main.py
  login: required

- url: ./info/.*
  script: main.py

- url: .*
  script: main.py
